import { useEffect, useMemo, useState } from 'react';
import { Archive, Building2, CheckCircle2, Download, ExternalLink, FileSpreadsheet, Folder, FolderPlus, Globe, LoaderCircle, MailCheck, MailQuestion, MapPin, RotateCcw, Search, Smartphone, Star, Trash2, WandSparkles } from 'lucide-react';
import useLeads from '../hooks/useLeads';
import Card from '../components/common/Card';
import { folderService, leadService, searchService } from '../services/api';

const isSent = (lead) => !['Novo Lead', 'Entrar em contato'].includes(lead.status || 'Novo Lead');

export default function CompaniesPage({ onSelectLead, refreshTrigger }) {
  const [query, setQuery] = useState(''); const [city, setCity] = useState(''); const [segment, setSegment] = useState('');
  const [searchId, setSearchId] = useState(''); const [contactFilter, setContactFilter] = useState('all');
  const [savedSearches, setSavedSearches] = useState([]); const [folders, setFolders] = useState([]); const [folderFilter, setFolderFilter] = useState('');
  const [targetFolder, setTargetFolder] = useState(''); const [newFolderName, setNewFolderName] = useState(''); const [selectedIds, setSelectedIds] = useState([]);
  const [bulkBusy, setBulkBusy] = useState(false); const [feedback, setFeedback] = useState(''); const [aiResult, setAiResult] = useState(null);
  const { leads, loading, cities, segments, updateLeadStatus, setLeads } = useLeads({ archived: 'all' }, refreshTrigger);

  const refreshFolders = () => folderService.getAll().then((data) => setFolders(Array.isArray(data) ? data : [])).catch(() => setFolders([]));
  useEffect(() => { Promise.all([searchService.getSaved().then((data) => setSavedSearches(Array.isArray(data) ? data : [])).catch(() => setSavedSearches([])), refreshFolders()]).catch(() => {}); }, [refreshTrigger]);

  const selectedSearchIds = useMemo(() => searchId ? new Set((savedSearches.find((item) => String(item.id) === searchId)?.leadIds || []).map(String)) : null, [savedSearches, searchId]);
  const selectedFolderIds = useMemo(() => folderFilter ? new Set((folders.find((folder) => folder.id === folderFilter)?.leadIds || []).map(String)) : null, [folders, folderFilter]);
  const filteredLeads = useMemo(() => leads.filter((lead) => {
    const term = query.trim().toLocaleLowerCase('pt-BR'); const haystack = `${lead.name || ''} ${lead.description || ''} ${lead.category || ''} ${lead.segment || ''}`.toLocaleLowerCase('pt-BR');
    return (!term || haystack.includes(term)) && (!city || lead.city === city) && (!segment || lead.segment === segment || lead.category === segment)
      && (!selectedSearchIds || selectedSearchIds.has(String(lead.id))) && (!selectedFolderIds || selectedFolderIds.has(String(lead.id)));
  }), [leads, query, city, segment, selectedSearchIds, selectedFolderIds]);
  const summary = useMemo(() => ({
    total: filteredLeads.filter((lead) => !lead.archived).length,
    pending: filteredLeads.filter((lead) => !lead.archived && !isSent(lead)).length,
    sent: filteredLeads.filter((lead) => !lead.archived && isSent(lead)).length,
    archived: filteredLeads.filter((lead) => lead.archived).length,
  }), [filteredLeads]);
  const visibleLeads = useMemo(() => filteredLeads.filter((lead) => {
    if (contactFilter === 'archived') return Boolean(lead.archived);
    if (lead.archived) return false;
    return contactFilter === 'all' || (contactFilter === 'sent' ? isSent(lead) : !isSent(lead));
  }), [filteredLeads, contactFilter]);
  const visibleIds = visibleLeads.map((lead) => String(lead.id)); const selectedSet = new Set(selectedIds);
  const allSelected = visibleIds.length > 0 && visibleIds.every((id) => selectedSet.has(id));
  const toggleSelected = (id) => setSelectedIds((current) => current.includes(String(id)) ? current.filter((item) => item !== String(id)) : [...current, String(id)]);
  const toggleAll = () => setSelectedIds(allSelected ? selectedIds.filter((id) => !visibleIds.includes(id)) : [...new Set([...selectedIds, ...visibleIds])]);

  const toggleSent = async (lead) => { setFeedback(''); await updateLeadStatus(lead.id, isSent(lead) ? 'Novo Lead' : 'Mensagem enviada'); setFeedback(isSent(lead) ? 'Contato reaberto e devolvido aos ativos.' : 'Contato enviado e movido para Arquivados.'); };
  const createFolder = async () => { if (!newFolderName.trim()) return; setBulkBusy(true); setFeedback(''); try { const folder = await folderService.create(newFolderName); await refreshFolders(); setTargetFolder(folder.id); setNewFolderName(''); setFeedback(`Pasta “${folder.name}” criada.`); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };
  const addToFolder = async () => { if (!selectedIds.length || !targetFolder) return setFeedback('Selecione empresas e uma pasta.'); setBulkBusy(true); try { const updated = await folderService.addLeads(targetFolder, selectedIds); await refreshFolders(); setFeedback(`${selectedIds.length} adicionada(s) à pasta “${updated.name}”.`); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };
  const removeFromCurrentFolder = async () => { if (!folderFilter || !selectedIds.length) return; setBulkBusy(true); try { await folderService.removeLeads(folderFilter, selectedIds); await refreshFolders(); setSelectedIds([]); setFeedback('Seleção removida da pasta.'); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };
  const deleteCurrentFolder = async () => { if (!folderFilter) return; setBulkBusy(true); try { await folderService.remove(folderFilter); setFolderFilter(''); await refreshFolders(); setFeedback('Pasta excluída. As empresas continuam salvas.'); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };
  const prioritize = async () => { if (!selectedIds.length) return setFeedback('Selecione as empresas que a IA deve comparar.'); setBulkBusy(true); setAiResult(null); try { setAiResult(await leadService.prioritize(selectedIds, 'Classifique por intenção provável, urgência observável, aderência aos serviços, facilidade de contato e melhor próxima ação.')); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };
  const archiveSelection = async (archived) => { if (!selectedIds.length) return setFeedback('Selecione ao menos uma empresa.'); setBulkBusy(true); try { const result = await leadService.setArchived(selectedIds, archived); const ids = new Set(selectedIds); setLeads((items) => items.map((lead) => ids.has(String(lead.id)) ? { ...lead, archived, archived_at: archived ? new Date().toISOString() : null } : lead)); setFeedback(`${result.updated} empresa(s) ${archived ? 'arquivada(s)' : 'restaurada(s)'}.`); setSelectedIds([]); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };
  const restoreLead = async (lead) => { setBulkBusy(true); try { await leadService.setArchived([lead.id], false); setLeads((items) => items.map((item) => String(item.id) === String(lead.id) ? { ...item, archived: false, archived_at: null } : item)); setFeedback(`${lead.name} restaurada.`); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };
  const exportContacts = async (format) => { const leadIds = selectedIds.length ? selectedIds : visibleIds; if (!leadIds.length) return setFeedback('Não há contatos para exportar.'); setBulkBusy(true); try { const result = await leadService.exportContacts(leadIds, format); const url = URL.createObjectURL(result.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.filename; anchor.style.display = 'none'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); setFeedback(`${result.exported} contato(s) exportado(s) em ${format.toUpperCase()}.`); } catch (err) { setFeedback(err.message); } finally { setBulkBusy(false); } };

  return <div className="animate-fade-in">
    <div className="company-directory-header"><div><h3>Base de empresas</h3><p>Selecione qualquer quantidade, exporte contatos e organize o que já foi abordado.</p></div><span className="directory-count">{summary.total} ativa{summary.total === 1 ? '' : 's'}</span></div>
    <div className="contact-summary-grid">
      <button type="button" className={contactFilter === 'all' ? 'active' : ''} onClick={() => setContactFilter('all')}><Building2 size={17}/><span><small>Ativos</small><strong>{summary.total}</strong></span></button>
      <button type="button" className={contactFilter === 'pending' ? 'active pending-filter' : 'pending-filter'} onClick={() => setContactFilter('pending')}><MailQuestion size={17}/><span><small>Não enviados</small><strong>{summary.pending}</strong></span></button>
      <button type="button" className={contactFilter === 'sent' ? 'active sent-filter' : 'sent-filter'} onClick={() => setContactFilter('sent')}><MailCheck size={17}/><span><small>Em andamento</small><strong>{summary.sent}</strong></span></button>
      <button type="button" className={contactFilter === 'archived' ? 'active archived-filter' : 'archived-filter'} onClick={() => setContactFilter('archived')}><Archive size={17}/><span><small>Arquivados</small><strong>{summary.archived}</strong></span></button>
    </div>
    <section className="folder-shelf"><div className="folder-shelf-title"><span><Folder size={16}/> Pastas</span><div className="folder-create"><input value={newFolderName} onChange={(event) => setNewFolderName(event.target.value)} placeholder="Criar nova pasta" maxLength={60}/><button type="button" onClick={createFolder} disabled={bulkBusy || !newFolderName.trim()}><FolderPlus size={16}/> Criar</button></div></div><div className="folder-chips"><button type="button" className={!folderFilter ? 'active' : ''} onClick={() => setFolderFilter('')}>Todas</button>{folders.map((folder) => <button type="button" className={folderFilter === folder.id ? 'active' : ''} key={folder.id} onClick={() => setFolderFilter(folder.id)}>{folder.name}<small>{folder.leadIds.length}</small></button>)}</div></section>
    <Card className="directory-filters"><div className="directory-search"><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por empresa ou descrição" aria-label="Buscar empresas"/></div><select value={city} onChange={(event) => setCity(event.target.value)}><option value="">Todas as cidades</option>{cities.map((item) => <option key={item}>{item}</option>)}</select><select value={segment} onChange={(event) => setSegment(event.target.value)}><option value="">Todos os nichos</option>{segments.map((item) => <option key={item}>{item}</option>)}</select><select value={searchId} onChange={(event) => setSearchId(event.target.value)}><option value="">Todas as buscas</option>{savedSearches.map((item) => <option key={item.id} value={item.id}>{item.query} · {item.city} · {item.found}/{item.requested}</option>)}</select></Card>
    <div className="bulk-toolbar captured-bulk"><label className="bulk-check"><input type="checkbox" checked={allSelected} onChange={toggleAll}/><span>{allSelected ? 'Desmarcar visíveis' : `Selecionar visíveis (${visibleIds.length})`}</span></label><select value={targetFolder} onChange={(event) => setTargetFolder(event.target.value)}><option value="">Pasta de destino</option>{folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><button type="button" className="bulk-primary" disabled={bulkBusy || !selectedIds.length || !targetFolder} onClick={addToFolder}>Adicionar {selectedIds.length || ''} à pasta</button><button type="button" className="bulk-ai" disabled={bulkBusy || !selectedIds.length} onClick={prioritize}>{bulkBusy ? <LoaderCircle className="spin" size={15}/> : <WandSparkles size={15}/>} Priorizar com IA</button><span className="export-divider"/><button type="button" className="bulk-export" disabled={bulkBusy || !visibleIds.length} onClick={() => exportContacts('vcf')}><Smartphone size={15}/> Celular</button><button type="button" className="bulk-export" disabled={bulkBusy || !visibleIds.length} onClick={() => exportContacts('txt')}><Download size={15}/> Números</button><button type="button" className="bulk-export excel" disabled={bulkBusy || !visibleIds.length} onClick={() => exportContacts('xlsx')}><FileSpreadsheet size={15}/> Excel</button>{contactFilter === 'archived' ? <button type="button" className="bulk-restore" disabled={bulkBusy || !selectedIds.length} onClick={() => archiveSelection(false)}><RotateCcw size={15}/> Restaurar</button> : <button type="button" className="bulk-archive" disabled={bulkBusy || !selectedIds.length} onClick={() => archiveSelection(true)}><Archive size={15}/> Arquivar</button>}{folderFilter && <button type="button" className="bulk-secondary" disabled={bulkBusy || !selectedIds.length} onClick={removeFromCurrentFolder}>Remover da pasta</button>}{folderFilter && <button type="button" className="folder-delete" disabled={bulkBusy} onClick={deleteCurrentFolder}><Trash2 size={15}/></button>}<small>{selectedIds.length ? `${selectedIds.length} selecionado(s) serão usados` : `Sem seleção: os ${visibleIds.length} visíveis serão exportados`}</small></div>
    {feedback && <div className="bulk-feedback">{feedback}</div>}
    {aiResult && <div className="ai-priority-panel"><div><strong>Plano de ataque sugerido</strong><span>{aiResult.provider === 'gemini' ? 'Gemini especialista' : 'Análise segura local'}</span></div><p>{aiResult.summary}</p><ol>{aiResult.recommendations.slice(0, 20).map((item) => { const lead = leads.find((entry) => String(entry.id) === item.leadId); return <li key={item.leadId}><strong>{lead?.name || 'Empresa'} · {item.score}/100</strong><span>{item.reason}</span><small>{item.approach}</small></li>; })}</ol></div>}
    {loading ? <p className="directory-empty">Carregando empresas...</p> : visibleLeads.length === 0 ? <p className="directory-empty">Nenhuma empresa encontrada com estes filtros.</p> : <div className="company-directory-grid">{visibleLeads.map((lead) => <article className={`company-directory-card ${selectedSet.has(String(lead.id)) ? 'selected' : ''} ${isSent(lead) ? 'contacted' : 'pending-contact'} ${lead.archived ? 'archived' : ''}`} key={lead.id} onClick={() => onSelectLead(lead.id)}><div className="company-directory-card-top"><label className="card-select" onClick={(event) => event.stopPropagation()}><input type="checkbox" checked={selectedSet.has(String(lead.id))} onChange={() => toggleSelected(lead.id)} aria-label={`Selecionar ${lead.name}`}/></label><span className="company-directory-icon"><Building2 size={18}/></span><span className={`score-pill ${lead.opportunity_score >= 80 ? 'high' : ''}`}>{lead.opportunity_score || 0}/100</span></div><strong>{lead.name}</strong><span className="company-directory-category">{lead.category || lead.segment || 'Empresa local'}</span><span className="company-directory-detail"><MapPin size={14}/>{lead.city || 'Localização não informada'}</span><span className="company-directory-detail"><Star size={14}/>{lead.rating ? `${lead.rating} (${lead.reviews_count || 0} avaliações)` : 'Sem avaliações'}</span><div className="company-directory-card-footer">{lead.website ? <span><Globe size={14}/> Site</span> : <span>Sem site</span>}<button type="button" onClick={(event) => { event.stopPropagation(); onSelectLead(lead.id); }}>Ver perfil <ExternalLink size={14}/></button></div>{lead.archived ? <button type="button" className="sent-toggle restore" onClick={(event) => { event.stopPropagation(); restoreLead(lead); }}><RotateCcw size={14}/>Restaurar contato</button> : <button type="button" className={`sent-toggle ${isSent(lead) ? 'sent' : ''}`} onClick={(event) => { event.stopPropagation(); toggleSent(lead); }}><CheckCircle2 size={14}/>{isSent(lead) ? 'Reabrir contato' : 'Marcar enviado e arquivar'}</button>}</article>)}</div>}
  </div>;
}
